FROM nvidia/cuda:10.0-base-ubuntu18.04

LABEL maitainer="Alexander Kalinovsky <alxkalinovsky@yandex.ru>"

RUN mkdir -p /workspace
WORKDIR /workspace
COPY pip-requirements.txt /workspace

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ Europe/Minsk


# (CPU.1) basic setup
RUN apt update && apt install -y --no-install-recommends \
    curl \
    less \
    mc \
    htop \
    iotop \
    nethogs \
    sshfs openssh-client \
    libspatialindex4v5 libspatialindex-c4v5 libspatialindex-dev \
    libfreetype6-dev \
    libhdf5-serial-dev \
    python3 python3-dev python3-pip python3-setuptools python3-tk \
    software-properties-common \
    build-essential \
    unzip \
    rsync \
    tmux \
    iputils-ping \
    net-tools \
    nmap \
    bash-completion \
    pkg-config && \
    echo "Europe/Minsk" > /etc/timezone && \
    apt-get install -y --no-install-recommends  && \
    pip3 --no-cache-dir install pip -U && \
    pip --no-cache-dir install setuptools -U && \
    pip --no-cache-dir install ipython matplotlib -U && \
    pip completion --bash >> ~/.bashrc && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*


RUN apt update && apt install -y --no-install-recommends libice6 libsm6 && \
    pip3 --no-cache-dir install -r /workspace/pip-requirements.txt && \
    pip3 install flower -U && \
    apt clean && rm -rf /var/lib/apt/lists/*


# (Python) install python packages
#RUN apt update && apt install -y --no-install-recommends libice6 libsm6 && \
#    pip3 --no-cache-dir install -r /workspace/pip-requirements.txt && \
#    pip3 install flower -U && \
#    apt clean && rm -rf /var/lib/apt/lists/*


